
FROM node:16-alpine AS base

WORKDIR "/app"

COPY package.json package.json
COPY package-lock.json package-lock.json
COPY tsconfig.build.json tsconfig.build.json
COPY tsconfig.json tsconfig.json
COPY src src

RUN npm install
RUN npm run build

FROM node:16-alpine AS final

WORKDIR "/app"

COPY --from=base /app/package.json ./package.json
COPY --from=base /app/package-lock.json ./package-lock.json
COPY --from=base /app/dist ./dist
COPY --from=base /app/node_modules ./node_modules

CMD [ "node", "dist/main"]